export const data = [
  {
    name: "API",
    description: "API template",
    url: "https://github.com/chepuhasasha/API",
    lang: "TypeScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Sun Jan 23 2022",
    commits: 0,
  },
  {
    name: "ASCII",
    description: null,
    url: "https://github.com/chepuhasasha/ASCII",
    lang: "Python",
    issues: 0,
    stars: 0,
    lastUpdate: "Wed Jan 19 2022",
    commits: 0,
  },
  {
    name: "chepuhasasha",
    description: "Config files for my GitHub profile.",
    url: "https://github.com/chepuhasasha/chepuhasasha",
    lang: "JavaScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Tue Sep 13 2022",
    commits: 0,
  },
  {
    name: "CLI",
    description: "CLI template",
    url: "https://github.com/chepuhasasha/CLI",
    lang: "JavaScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Tue Jan 18 2022",
    commits: 0,
  },
  {
    name: "muup",
    description: null,
    url: "https://github.com/chepuhasasha/muup",
    lang: "Vue",
    issues: 0,
    stars: 0,
    lastUpdate: "Tue Sep 13 2022",
    commits: 0,
  },
  {
    name: "nestjs",
    description: null,
    url: "https://github.com/chepuhasasha/nestjs",
    lang: "TypeScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Fri Mar 11 2022",
    commits: 0,
  },
  {
    name: "ois",
    description: null,
    url: "https://github.com/chepuhasasha/ois",
    lang: "TypeScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Thu Jun 23 2022",
    commits: 0,
  },
  {
    name: "snowblower",
    description:
      "Данный проект был реализован в рамках хакатона, Цифровой прорыв, в общей сложности за 48 часов.",
    url: "https://github.com/chepuhasasha/snowblower",
    lang: "Vue",
    issues: 0,
    stars: 1,
    lastUpdate: "Fri Nov 12 2021",
    commits: 0,
  },
  {
    name: "v-container",
    description: "This plugin for VUE makes it easy to set up block geometry.",
    url: "https://github.com/chepuhasasha/v-container",
    lang: "TypeScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Thu May 19 2022",
    commits: 0,
  },
  {
    name: "v-lang",
    description:
      "This plugin for VUE is designed to save you from having to maintain language dictionaries for the text content of your Vuejs application and make it easier to localize it. If you are tired of the endless naming of variables in the language dictionary, this plugin is for you.",
    url: "https://github.com/chepuhasasha/v-lang",
    lang: "TypeScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Thu May 19 2022",
    commits: 0,
  },
  {
    name: "v-theme",
    description: "Plugin for convenient organization of your style variables.",
    url: "https://github.com/chepuhasasha/v-theme",
    lang: "TypeScript",
    issues: 0,
    stars: 0,
    lastUpdate: "Thu May 19 2022",
    commits: 0,
  },
  {
    name: "vng",
    description: null,
    url: "https://github.com/chepuhasasha/vng",
    lang: "Jupyter Notebook",
    issues: 0,
    stars: 0,
    lastUpdate: "Thu Nov 11 2021",
    commits: 0,
  },
];
